import pandas as pd 
tweets=pd.read_csv("tweets_3k_annotated.csv",sep =',')
my_list2=[['SOCIAL ARTIST'], [], [], ['fast food music'], ['Portugal'], [], [], [], ['Albert Einstein'], [], ['United Kingdom', 'United Kingdom', 'Ukraine'], ['United Kingdom', 'United Kingdom', 'London', 'Ukraine'], [], [], [], ['Spain'], [], [], ['Norway'], ['Europe'], [], [], [], [], [], [], ['president', 'Ukraine'], ['Kiev'], ['UN'], [], ['Roger Pontare'], [], ['Mike Dean', 'Liberty University'], ['Mike Dean', 'Liberty University'], ['Mike Dean', 'Sophie Turner', 'Joe Jonas', 'Liberty University'], ['Liberty University', 'Mike Dean'], ['Mike Dean', 'Liberty University'], [], [], [], [], [], [], [], [], [], [], ['Rotherham', 'Bradford', 'America'], ['David guetta'], [], ['Belgium', 'Moldova', 'Portugal'], ['Odessa', 'journalist', 'Buzina'], [], [], [], [], [], [], [], [], ['British Isles', 'the British Isles'], [], [], [], [], [], [], [], ['Liam e Niall', 'San Diego'], [], [], [], ['Instagram'], [], [], [], [], [], ['Instagram', 'Snapchat'], ['Instagram'], ['LIAM TONIGHT'], ['"On The Loose"'], [], [], [], ['High School Baseball Player'], [], ['Niall Cantando'], [], [], [], [], [], [], [], [], [], [], ['Together\nNiall Horan', 'Liam Payne', 'Payne'], [], ['Avril Lavigne', 'Avril'], ['Stubhub'], [], [], ['102.7 KIIS FM'], [], [], [], ['Wango Tango', '102.7 KIIS FM'], [], [], ['US', 'LIAM SURPRISES'], ['Instagram'], [], [], ['Instagram'], [], [], ['Portugal'], [], [], [], [], [], [], [], ['"STAY"'], [], [], [], [], [], [], [], [], [], [], ['the Prince'], [], [], [], [], [], [], ['Instagram'], [], [], [], ['Prince', 'Prince'], [], [], [], [], ['PRINCE', 'PRINCE', 'ADAM LEVINE'], [], [], ['Instagram'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Malibu'], [], ['LIAM VIENDO'], [], [], [], [], ['Miley', 'her'], [], ['Bon Appétit'], [], [], ['Prince'], [], [], [], [], ['ADAM'], [], ['LIAM PAYNE'], [], [], [], [], ['Snapchat'], [], [], [], [], [], [], [], [], [], [], ['NIALL MY'], [], ['Wango Tango'], [], [], ['Camila Cabello'], ['Instagram', 'Snapchat', 'Queen'], [], [], [], ['"Let\'s Go Crazy"', 'Adam', 'the Prince'], [], [], [], ['Fisher'], [],[], ['102.7 KIIS FM'], ['Niall', 'Harry'], ['Snapchat', 'Instagram'], ['Instagram', 'RT'], [], [], ['"On The Loose"'], [], [], [], [], [], [], [], [], [], ['Instagram'], [], [], [], [], ['DREAM'], [], [], [], [], [], [], [], ['Instagram'], ['heart attack'], ['"Let\'s Go Crazy"'], [], [], ['"Malibu"'], ['Dolly Parton'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Wango Tango'], ['Prince', 'Prince'], [], [], [], [], ['Snapchat'], ['Bryce Harper'], [], ['Instagram'], [], ['first  Village artist'], [], ['Mercedes F015'], [], [], [], [], ['Hold Tight'], [], [], [], [], [], ['Los Angeles', 'Wango Tango'], [], [], [], ['Instagram'], [], [], [], [], [], [], [], [], ['Camila Cabello'], [], [], [], [], [], ['Katy Perry Performing'], [], [], [], [], [], ['Snapchat', 'RT'], [], [], [], [], ['artist'], [], [], [], [], [], [], ['adam'], ['Leeds Bradford Airport', 'Kate Bush'], ['Adam Levine'], ['Queen'], [], ['Max b'], ['NIALL LIAM', 'LIAM NIALL LIAM NIALL', 'LIAM NIALL LIAM NIALL', 'LIAM NIALL LIAM NIALL', 'LIAM NIALL LIAM NIALL', 'LIAM', 'NIALL  NIALL LIAM NIALL', 'NIALL LIAM NIALL LIAM', 'NIALL LIAM NIALL LIAM', 'NIALL LIAM NIALL LIAM', 'NIALL LIAM NIALL LIAM', 'NIALL LIAM NIALL LIAM'], [], [], ['Snapchat'], [], [], [], [], ['102.7 KIIS FM', '"Eyes Closed"'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['San Diego'], [], [], [], [], [], [], [], [], [], ['102.7 KIIS FM', 'California'], [], [], ['102.7 KIIS FM'], [], ['LIAM EN'], [], ['M&G'], [], ['102.7 KIIS FM'], [], [], [], [], ['Instagram'], [], [], [], [], ["'On the Loose'"], [], [], ['Liam Payne'], [], ['Liam Payne', 'Sofia Carson', 'Jordan Fisher', 'Wango Tango'], [], ['⒈ \n⒉ Woodley\n⒊ \n⒋ Kate Bush\n⒌ Leeds Bradford Airport'], [], [], [], [], [],[], [], [], [], [], [], [], [], ['PRINCE', 'PRINCE'], ['Instagram'], [], [], [], ['"On The Loose"'], ['102.7 KIIS FM', 'Cali'], [], [], [], ['We Can'], [], [], [], [], [], [], [], ['WANGO TANGO'], [], [], [], [], [], ['Instagram'], ["'On the Loose'"], [], [], [], ['Prince', 'Prince', '"Let\'s Go Crazy"'], [], [], [], [], [], ['queen'], [], [], [], [], [], [], [], [], ['CAMILA CABELLO'], [], [], [], ['Instagram'], [], [], [], ['Instagram'], [], [], [], ['Dark Horse'], [], [], [], [], [], ['Instagram'], [], [], ['Instagram'], [], [], [], [], ['LIAM SINGLE', 'HARRY CANTANDO SC'], [], [], [], ['Queen'], ['Jimmy Fallon', 'Chris Pratt'], [], [], [], [], [], ['Portugal'],['Bobby Ryan'], [], ['Snapchat'], [], [], [], [], [], [], ['"Slow Hands"'], [], ['Snapchat'], [], [], [], [], ['Dark Horse', 'Bon Appétit', 'Bon Appétit'], [], ['Lenovo', 'Google'], [], [], [], [], [], [], [], ['We Can'], ['ADAM LEVINE'], [], [], [], [], ['"On The Loose"'], [], [], [], [], [], [], [], [], [], [], ['"I Want Candy"'], [], ['Geli', 'Stella'], [], [], [], [], [], [], ['Instagram'], [], [], [], [], [], ['Niall Horan'], [],[], [], [], [], [], [], [], [], ['Children'], [], [], [], [], [], [], [], [], [], [], [], [], ['USA', 'RT'], [], [], [], [], [], [], [], [], [], [], ['your plastic surgeon'], ['rt'], [], [], [], [], ['GOP'], [], [], [], [], ['America'], [], [], [], [], ['Liberty University'], [], [], [], [], [], [], [], ['Google', 'Juno Mission'], [], [], [], [],[], [], [], [], [], [], [], ['GOP'], [], ['Bill'], [], [], [], [], [], [], ['Twitter'], [], [], [], [], [], [], [], ['America'], ['KKK'], [], [], [], [], ['Vladimir Caddie'], [], [], [], [], ['Africa', 'India', 'Asia'], ['Twitter'], [], [], [], ['GOP'], ['a special prosecutor'], [], [], [], [], [], ['Tower of Babel Real'], [], [], [], [], [], [], [], [], [], [], ['Dentist', 'Dentist'], ['The Left'], [], [], [],[], ['America'], ['Hillary Clinton'], [], [], [], [], [], [], [], [], [], [], [], [], ['Hitler'], ['crack head'], [], [], [], [], [], [], ['US'], [], [], [], [], ['professor'], [], [], ['Turkey'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Flip & RT'], ['George Soros', 'he'],[], [], [], [], [], [], [], ['food t', 'Officer', 'William Stacy', 'he'], ['Congress'], [], [], [], [], [], ['America'], [], [], [], [], [], [], [], [], [], [], ['North America'], [], ['Russia'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Twitter'], [], ['Hitler'], [], [], [], [], [], [], [], [], [], ['South Africa'], [], [], [], [], [], [], [], [], [], [], [], [], ['George Soros', 'Europe'], ['gas chambers'], [], [], [], [], [], ['President', 'first white president', 'Trump'], [], [], [], [], [], [], [], [], [], ['Pepe'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Lincoln'], [], [], [],[], [], ['Bill Clinton', 'his', 'TB', 'Hillary'], [], [], ['Eminem'], [], [], [], [], [], [], [], [],[],[], [], [], [], [], [], [], [], [], [], [], [], [], ['America'], [], [], ['Russia', 'Russia!'], [], [], ['Twitter'], [], [], ['Canada'], ['Twitter'], [], [], [], [], [], [], [], ['KKK'], [], [], [], ['America'], [], [], ['anti-Christian'], [], [], ['oil/resources'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['The Left'], ['Democratic Party', 'Democratic Party', 'Republican Party'], [], [], [], [], [], [], ['Michigan'], [], [], [], [], [], [], [], ['Sheila Jackson', 'her', 'she'], ['RT'], [], ['representative'], [], [], [], [], [], ['Bobby Ryan', 'Ariel Winter'], ['America'], [], ['America'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['American government'], [], [], [], [], ['Liberty University'], [],['Congress'], [], [], ['America'], [], [], [], [], ['Twitter'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['USA', 'New  Party'], [], [], [], [], [], [], [], [], ['Poland', 'Vienna', 'Turkey'], [], ['President'], [], [], [], ['Democrat Party', 'racist party'], [], [], [], [], ['Liberty University'], [], [], [], ['Hillary Clinton'], [], [], ['@Stevenwhirsch99 @Shalom555222 People RT'], [], [], [], [], ['Twitter'],[], [], [], [], [], [], [], [], [], ['Martin Luther King Jr'], [], [], [], [], [], [], [], [], [], ['250 RT', 'RT'], [], [], [], ['Frankie Edgar', 'Conor McGregor'], [], ['Jorge Masvidal', 'him', 'head'], [], [], [], [], [], ['Carlos Condit'], [], [], [], [], [], [], [], [], [], [], ['looking forward'], ['Demian Maia', 'his'], [], [], [], ['RT'], ['Brazil'], [], [], [], [], [], [], [], [], ['Frankie Edgar'],[], [], [], ['Kendrick Lamar', 'Bobby Ryan'], [], [], ['Frankie Edgar'], ['Hope Maia'], ['Mississippi', 'Jason Knight'], ['Bruce Buffer'], [], [], [], [], ['Frankie Edgar'], [], [], [], [], [], [], [], ['Scarface'], [], [], [], ['Awesome commentator', 'Daniel Cormier'], [], [], [], [], [], [],[], [], ['Joe Silva'], [], [], [], ['CNN'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Demian Maia'], [], [], ['Demian Maia'], [], [], ['JOE SILVA'], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Uber'], [], ['Frankie Edgar', 'Yair'], [], [], ['Scarface'], [], ['@ufc'], [], ['Frankie Edgar'], [], [], [], [], [], ['Jorge "Gamebred" Masvidal', 'Demian Maia'],[], [], [], ['atm'], ['Joe Silva'], ['Demian Maia'], [], [], [], [], [], [], ['Chase Sherman', 'Rashad Coulter'], [], [], [], [], [], [], [], [], [], ['Wow!'], [], [], [], [], [], [], [], [], [], ['CNN'], ['RT'], [], [], [], ['imo'], [], [], [], [], [], ['Frankie Edgar'], ['RT'], [], [], [], ['media row'], [], [], ['the executioner'], ['Frankie Edgar'], [], [], ['Frankie Edgar'], [], ['Wow!'], [], [], ['David Branch'], [], [], [], [], ['Frankie Edgar'], [], [], [], [], [], [], [], [], [], [], [], ['Haha'], [], [], [], [], [], [], ['Scarface'], [], [], ['Demian Maia'], ['Jorge Masvidal'], [], [], [], [], [], [], [], [], ['TMT Boxer', 'Bobby Ryan', 'Uber'], ['DEMIAN WHAT'], [], [], [], [], ['Prison Rules', 'Eddie Alvarez'], [], [], ['Maia v Masvidal', 'Maia'], [], [],[], [], [], [], [], [], [], [], [], [], ['Jorge Masvidal'], [], ['Demian Maia'], [], ['Joe Silva'], [], ['Welterweights square'], ['Frankie Ed', 'Alex Caceres'], [], ['Frankie Edwards'], ['Scarface'], [], ['Eminem', 'Lincoln Park', 'his'],[], [], ['Welterweights square'], [], [], [], [], [], ['Joe Silva'], [], [], [], [], [], [], ['George Soros', 'he'], [], [], [], [], [], ['Jessica Andrade', 'Joanna Jedrzejczyk'], [], ['Frankie Edgar'], [], [], [], ['Scarface'], [], ['Frankie Edgar'], [], [], [], [], [], [], [], [], ['RT'], [], [], ['Frankie Edgar'], ['Frankie Edgar'], ['Dos', 'Santos'], [], ['Frankie Edgar'], [], [], [], [], [], [], [], [], [], [], [], [],[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['Rick Story', 'his'], [], ['Frankie Edgar'], [], [], [], [], [], [], ['Demian Maia', 'his'], ['Damian Maia', 'Jorge Masvidal'], [], [], [], [], [], ['Dustin Poirier'], [], ['Frankie Edgar'], [], [], [], [], ['Demian Maia', 'Ya Gano RT'], [], [], [], [], [], ['Texas', 'Texas'], [], [], [], ['Damian Maia'], [], [], [],['Frankie Edgar'], [], [], [], [], [], [], [], ['Frankie Edgar', 'Edgar'], ['Frankie Edgar'], [], [], ['Masvidal'], [], [], [], [], ['MMA Tycoon league'], [], [], [], [], [], [], ['Demian Maia', 'he', 'his'], [], [], ['Chester Bennington', 'Damian Maia', 'he'], [], [], ['IMO'], [], ['Matt Brown', 'Carlos Condit'], [], [], [], [], [], ['Frankie Edgar'], [], [], [], [], [], ['Demian Maia'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], ['game technician'], [], [], [], ['Jorge Masvidal', 'Demian Maia'], ['car accident'], [], [], [], [],[], [], [], [], ['Maia v Masvidal'], [], [], [], [], [], [], [], ['Jorge Masvidal'], [], [], [], [], ['Frankie Edgar'], [], [], [], [], [], ['Demian Maia'], [], [], [], ['YouTube', 'Frankie Edgar'], [], [], [], [], [], [], [], ['Demian Maia', 'him'], [], [], [], ['Scarface'], [], ['Brasil'], [], [], []]
my_list=[['Trump Aide', 'FBI', 'Russian Government'],
[],
['FISA', 'Carter Page'],
[],
['Sean Spicer'],
['FBI'],
['Carter Page'],
['Flynn', 'he', 'his'],
[],
[],
['Susan Rice'],
['Carter Page'],
['the Trump advisor', 'Trump Tower', 'Carter Page', 'He'],
['Savior'],
['Carter Page', 'him', 'him'],
['aide', 'Carter Page', 'FBI'],
['adviser', 'FBI', 'Carter Page'],
['Russia'],
['Maxine Waters'],
['Russia', 'Carter Page', 'FBI'],
['adviser', 'The Washington Post', 'The Washington Post', 'FBI', 'Carter Page'],
['Carter Page'],
[],
['Carter page', 'FBI', 'Chris Hayes'],
['adviser', 'Carter Page', 'FBI'],
['US'],
[],
['DOJ', 'Carter Page', 'Sean Spicer'],
['Carter Page', 'Syria'],
['Russia', 'FBI', 'Carter Page', 'he'],
['adviser', 'FBI', 'Carter Page'],
['this spy'],
[],
['Carter Page', 'FBI'],
['carter page', 'carter page'],
[],
['Carter Page', 'he'],
[],
['adviser', 'The Washington Post', 'The Washington Post', 'FBI', 'Carter Page'],
['Carter Page', 'he'],
[],
[],
[],
[],
['FBI', 'Trump adviser', 'Carter Page'],
[],
['FBI', 'Trump adviser', 'Carter Page'],
['Carter Page', 'healthcare', 'GOP'],
[],
['Russia', 'FBI', 'Carter Page', 'adviser'],
['Carter Page', 'FBI', 'FBI', 'King'],
['FBI', 'Carter Page', 'adviser'],
['US'],
[],
[],
['Carter Page', 'he', 'he', 'White House'],
['Carter Page'],
['FBI', 'Carter Page', 'adviser'],
[],
['carter page', 'FBI'],
[],
[],
[],
['Comey', 'his'],
['Andrew McCabe', 'Carter Page', 'FBI'],
[],
['FISA court', 'FBI', 'Carter Page', 'adviser'],
[],
[],
['Carter Page', 'Adviser'],
[],
[],
[],
[],
['advisor', 'FBI', 'Russia'],
['Carter Page', 'him'],
['Carter Page', 'adviser', 'FBI'],
['Passover'],
['Director for election tampering too', 'FBI', 'James Comey'],
['Carter Page'],
['Carter Page', 'FBI'],
['Trump administration'],
['Carter Page', 'he', 'Russia'],
['Carter Page', 'Susan Rice'],
[],
['Carter Page', 'Trump Advisor', 'FBI'],
[],
['Carter Page', 'he', 'he'],
['Sam Clovis'],
[],
['FBI', 'FISA judge'],
[],
[],
['Sean Spicer'],
[],
[],
['Carter Page', 'FBI', 'aide'],
['Carter Page', 'monitor Trump adviser', 'FBI', 'Russia'],
[],
[],
['Washington Post', 'Washington Post', 'FBI', 'Carter Page', 'adviser'],
['Washington Post', 'FBI', 'FBI', 'Carter Page', 'adviser'],
['Carter Page'],
[],
['Justice Department', 'FBI'],
['carter page'],
[],
['Carter Page', 'Devin Nunes'],
['Carter Page'],
[],
[],
[],
[],
['Mr. Asshole Yellow', 'Gen. Flynn', 'Gen.'],
['Carter Page'],
['Carter Page'],
['Germany'],
['Carter Page'],
[],
[],
['stupid email server', 'FBI'],
[],
['Carter Page'],
[],
['Carter Page', 'his', 'Russia', 'Intel'],
['FBI'],
['Clinton', 'Carter Page', 'FBI'],
['FBI', 'Carter Page', 'adviser'],
['Sam Clovis'],
['Clinton'],
[],
[],
[],
[],
['Carter Page', 'Trump adviser', 'FBI'],
[],
['Carter Page', 'FBI', 'Russia'],
['Judy Without', 'Carter Page'],
['FBI', 'Russia', 'Carter Page', 'his'],
[],
['Carter Page', 'a judge'],
[],
[],
['Maxine Waters', 'Russia'],
['FISA warrant 2monitor Trump policy adviser', 'probable cause DT aide', 'Carter Page', 'FBI'],
['Carter Page'],
['Carter Page', 'FBI'],
['Carter Page'],
['Carter Page'],
['DEM', 'GOP'],
['Carter Page'],
[],
['FBI', 'tangled web', 'Intel'],
['Trump & Co.', 'FBI'],
[],
['Carter Page'],
['Acting Atty General'],
['adviser', 'FBI', 'Carter Page'],
[],
['Carter Page'],
['fbi'],
[],
['Chris Hayes'],
['the Carter Page FISA news'],
['Hillary Clinton', 'FBI', 'Carter Page'],
[],
['adviser', 'FBI', 'Carter Page'],
['Adviser', 'FBI', 'Carter Page'],
[],
[],
['Carter Page'],
['Obama administration', 'national security intelligence', 'IRS'],
['Devin Nunes', 'United Airlines', 'Carter Page', 'Sean Spicer'],
['FBI'],
[],
['Luther King', 'FBI', 'Carter Page', 'him', 'Hitler', 'Sean Spicer'],
[],
[],
[],
[],
[],
['adviser', 'FBI', 'Carter Page'],
[],
['Carter Page'],
['oil', 'Carter Page', 'him', 'the oil industry consultant'],
['Washington Post', 'Carter Page', 'Washington Post'],
['US', 'Russia Oil', 'CEO', 'Trump adviser', 'Russia Oil offered Trump adviser he felt deal to get US sanctions'],
[],
['FBI', 'Carter Page', 'adviser'],
['FBI'],
[],
['Carter Page'],
['Carter Page'],
[],
['Russia'],
['Carter Page', 'Russia'],
['FBI'],
[],
['Carter Page'],
['@LouiseMensch @MelissaJPeltier @RVAwonk'],
[],
['adviser', 'FBI', 'Carter Page'],
[],
[],
['a spy', 'Russia', 'foreign policy advisor'],
[],
[],
['adviser', 'FBI', 'Carter Page', 'The Washington Post', 'The Washington Post'],
['Carter Page'],
['carter page'],
['Susan Rice', 'USA'],
['Sean Spicer', 'Carter Page'],
['Russia'],
[],
['FISA court', 'Carter Page', 'a diplomat'],
['U.S.', 'Russia', 'Sean Spicer  Carter Page'],
['Trump aide', 'Judge', 'FBI', 'Carter Page'],
['FBI', 'Russia', 'Carter Page'],
['adviser', 'WHO', 'FBI', 'Carter Page', 'The Washington Post'],
[],
['Carter Page'],
['Washington Post', 'adviser', 'FBI', 'FBI', 'Washington Post', 'Washington Post', 'Carter Page'],
['Carter Page', 'advisor'],
['Sean Spicer', 'Carter Page', 'Christmas', 'Devin Nunes'],
['Congress', 'Carter Page'],
[],
['Carter Page'],
['Russia'],
['FBI', 'Russia', 'Washington Post', 'Carter Page', 'adviser'],
['United States Foreign Intelligence Surveillance Court', 'advisor', 'Carter Page'],
[],
['FBI', 'Carter Page'],
[],
[],
['Washington Post', 'adviser', 'Washington Post', 'FBI', 'Carter Page'],
['Trump adviser', 'FBI', 'Carter Page'],
['Washington Post', 'adviser', 'Washington Post', 'FBI', 'Carter Page'],
[],
['Putin', 'FBI'],
['Washington Post', 'Washington Post', 'MSNBC', 'Chris Hayes'],
['FBI', 'aide', 'Carter Page'],
['Carter Page'],
[],
['Carter Page', 'FBI'],
['Russia', 'Carter Page'],
[],
['King', 'THE URALS', 'Carter Page'],
[],
['energy', 'America', 'energy businessman', 'Putin', 'carter page', 'he'],
['FBI', 'Carter Page'],
[],
[],
[],
['Campaign Manager', 'Manaford'],
[],
['FISA court', 'America', 'FBI'],
['US', 'Carter Page'],
[],
['FBI', 'Carter Page', 'adviser'],
['Pepsi', 'Sean Spicer', 'Sean Spicer', 'Carter Page'],
['adviser', 'FBI', 'Carter Page'],
[],
['commission and special counsel', 'Devin Nunes', 'Carter Page'],
['FBI', 'adviser', 'Carter Page'],
['Sean Spicer Carter Page'],
[],
['Carter Page'],
[],
[],
[],
[],
['Russia'],
[],
['CNN'],
['FBI', 'adviser', 'Carter Page'],
[],
['FBI'],
['Carter Page'],
[],
[],
['Russia', 'Carter Page', 'Sean Spicer'],
['Carter Page', 'FBI'],
[],
['adviser', 'Carter Page'],
['FBI'],
[],
['Susan Rice', 'Carter Page', 'Sean Spicer', 'his', 'GOP'],
[],
['Carter Page'],
['adviser', 'Russia', 'Carter Page', 'he', 'FBI'],
['fbi'],
['Carter Page', 'Sean Spicer', 'Reporter'],
[],
['Carter Page', 'Mike Flynn'],
['Carter Page', 'FBI', 'adviser'],
['Russian intelligence', 'advisors'],
['Carter Page'],
[],
['carter page'],
['Carter Page', 'president'],
['Carter Page'],
['Carter Page'],
['FBI', 'Moscow'],
[],
['FISA court'],
['Carter Page', 'a foreign operative', 'The LATEST news'],
['adviser'],
[],
[],
[],
[],
['The Washington Post', 'FBI', 'adviser', 'Carter Page'],
['Russia', '@oreillyfactor Trump advisor'],
['Washington Post', 'FBI', 'Washington Post', 'adviser', 'Carter Page'],
['Carter Page', 'FBI', 'Andrew McCabe'],
['Putin'],
[],
['FISA Court'],
[],
[],
['Washington Post', 'adviser', 'Carter Page', 'FBI'],
['FBI', 'Carter Page', 'DT advisor'],
['adviser', 'Carter Page', 'FBI'],
['Carter Page', 'FBI', 'Trump adviser'],
['Nunes', 'Carter Page'],
[],
[],
['Carter Page, PhD'],
['the Korean Peninsula'],
['MSNBC'],
['Carter Page', 'Syria', 'Devin Nunes'],
['CARTER PAGE', 'Syria'],
['FBI', 'The Washington Post', 'Carter Page', 'adviser'],
['Carter Page', 'FBI', 'Adviser'],
['FBI', 'Carter Page', 'adviser', 'FISA court'],
['FBI', 'Carter Page'],
['FBI', 'Carter Page', 'adviser'],
['FBI', 'Carter Page', 'adviser'],
['FBI', 'Director Comey'],
['Carter Page'],
['an advisor', 'president of the United States was', 'United States'],
[],
['Carter Page', 'Hitler'],
['FBI'],
['FBI', 'Carter Page', 'Washington Post', 'adviser', 'Washington Post'],
['Carter Page', 'Washington Post', 'Washington Post', 'adviser'],
['FBI', 'FISA court'],
[],
['Carter Page'],
[],
['Carter Page'],
[],
['FBI'],
['Trump camp', 'Moscow'],
['FBI', 'Carter Page', 'adviser'],
['Russia', 'Sean Spicer Carter Page'],
['Carter Page', 'he', 'a spy', 'spy'],
['FBI', 'FBI', 'Clinton', 'Twitter', 'FISA court'],
['Carter Page'],
['Carter Page', 'Russia'],
['Carter Page', 'aide', 'FBI'],
['Carter Page', 'he'],
[],
[],
['FBI'],
['FBI', 'Carter Page', 'Hitler'],
[],
['Carter Page'],
[],
['U.S.'],
['Carter Page'],
['America', 'Tom Clancy'],
['Carter Page', 'FBI', 'FBI', 'adviser'],
[],
['carter page', 'beverage'],
[],
[],
['Russia', 'SYRIA'],
['FBI'],
[],
['FBI', 'Carter Page', 'adviser'],
[],
['Carter Page', 'he', 'he'],
['FBI', 'Carter Page', 'adviser'],
['Russia', 'FBI', 'Carter Page', 'adviser'],
['Carter Page', 'Rosneft', 'Russia', 'oil giant & Trump advisor', 'oil giant'],
[],
[],
['Carter Page', 'FBI'],
['FBI', 'adviser'],
['Russia', 'body guard for protection'],
['Carter Page', 'he'],
['Carter Page'],
['Carter Page', 'FBI'],
['FBI', 'Carter Page'],
['Syria', 'carter page', 'Don'],
['Carter Page'],
[],
[],
[],
['Carter Page', 'FBI', 'adviser'],
['Russia', 'FBI'],
['Carter Page'],
['Carter Page', 'he', 'FBI', 'adviser'],
['a Special Prosecutor'],
[],
['Susan Rice'],
['Carter Page'],
['FBI', 'Carter Page', 'Adviser'],
['FISA judge'],
['Russia'],
[],
['Carter Page'],
['Milano', 'Carter Page', 'his'],
['Carter Page', 'Russia'],
[],
[],
[],
[],
[],
['Senate', 'Roe v. Wade'],
[],
['FBI', 'Carter Page', 'Andrew McCabe'],
['FBI', 'Carter Page', 'adviser'],
['the Washington Post', 'the Washington Post', 'Carter Page', 'Trump', 'an advisor'],
['Russia', 'Carter Page', 'GOP', 'oil industry consultant', 'oil'],
['..Lawyer', 'Congress'],
[],
[],
['Russia', 'fbi'],
['Trump advisor'],
['Carter Page', 'him', 'FBI', 'Russia', 'Donald Trump'],
[],
[],
['Carter Page'],
[],
['Carter Page'],
[],
['Taylor Soldier Spicoli'],
[],
[],
['FBI', 'The Washington Post', 'Carter Page', 'The Washington Post', 'adviser'],
['Carter Page'],
['John Fugelsang'],
['Andrew McCabe', 'FBI', 'Carter Page'],
['FBI', 'Carter Page'],
[],
['FBI', 'Carter Page'],
[],
['Carter Page'],
[],
['Carter Page'],
['FBI', 'Carter Page', 'he', 'James Comey', 'he'],
[],
['Carter Page'],
['adviser', 'Carter Page\nDrip', 'FBI', 'Carter Page'],
['Carter Page'],
['Moscow', 'Carter Page', 'GOP'],
['adviser', 'Russian government', 'FBI'],
[],
['Carter Page'],
[],
[],
['Carter Page'],
[],
['FBI', 'adviser', 'Carter Page'],
["Bill O'Reilly", 'FISA court', 'FBI'],
['McDonald', 'Mike Vick'],
['adviser', 'FBI', 'Carter Page'],
['RT', 'Acting Atty General'],
['Foreign Policy Advisor', 'Russia', 'FBI'],
[],
['Washington Post', 'Washington Post', 'Carter Page', 'Page', 'adviser', 'FBI'],
['trumps campaign adviser', 'FBI', 'FBI', 'Carter Page'],
['DOJ', 'Wow!'],
['FBI', 'Russia'],
['Carter Page', 'He', 'Moscow'],
[],
[],
[],
[],
[],
['Carter Page'],
['Russia'],
['US'],
['Carter Page'],
[],
['Hitler', 'Carter Page'],
['carter page'],
['Carter Page', 'Clinton'],
[],
[],
['adviser', 'FBI', 'Carter Page'],
['Carter Page'],
['Carter Page', 'FBI', 'adviser'],
[],
['Paul Manafort', 'Russia'],
['FBI', 'Carter Page', 'aide'],
['Syria', 'Chechnya', 'Carter Page'],
[],
[],
['adviser', 'Carter Page', 'The Washington Post', 'The Washington Post', 'FBI'],
['Carter Page'],
['adviser', 'Trump', 'Trump', 'FBI', 'Carter Page'],
[],
['Russia'],
[],
[],
['spy'],
['The Washington Post', 'The Washington Post', 'adviser', 'FBI', 'Carter Page'],
['adviser', 'FBI', 'Carter Page'],
[],
['Trump advisors', 'a Trump advisor', 'Carter Page'],
[],
['Russia'],
['Trump adviser', 'Carter Page', 'FISA court', 'FBI'],
['adviser', 'Fox News', 'FBI'],
[],
[],
[],
['Russia'],
['Prince', 'Prince Kushner', 'campaign adviser', 'Prince'],
[],
['FBI'],
['Washington Post', 'adviser', 'Washington Post', 'FBI', 'Carter Page'],
[],
[],
['FBI', 'FISA court'],
['adviser', 'Greg Leppert', 'FBI', 'Carter Page'],
[],
['FBI', 'Carter Page'],
[],
['Russia', 'Russia!', 'Carter Page', 'he'],
['Carter Page'],
['Carter Page', 'him', 'FBI', 'Martin Luther King'],
['adviser', 'FBI', 'Carter Page'],
['FBI', 'Carter Page', 'a Trump advisor'],
['Carter Page'],
['Sean Spicer', 'Carter Page'],
[],
['adviser', 'FBI', 'FBI', 'Carter Page'],
[],
['fbi'],
[],
[],
['Adviser', 'FBI', 'Carter Page'],
['russia'],
['Carter Page', 'a Trump advisor'],
[],
[],
[],
[],
[],
['House of Representatives'],
['Congress', 'representative'],
[],
['MSM'],
[],
[],
['pre existing healthcare', 'coal mining states'],
['Michigan', 'congressman', 'Senate'],
[],
[],
['Senate'],
['Lawrence Does'],
[],
['GOP'],
['A Health Plan CEO'],
[],
[],
[],
['Jesus Christ'],
[],
[],
[],
[],
[],
[],
[],
['GOP'],
['Senate'],
[],
['insurance companies'],
[],
[],
[],
[],
['insurance giants'],
[],
['Congress'],
['Jason Blossom'],
[],
['GOP', 'Heineken'],
['Congress'],
[],
['House', 'Washington Post', 'Washington Post'],
[],
['America', 'KKK'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['GOP'],
['Ann Courter'],
[],
[],
[],
[],
[],
['disease'],
[],
['Dave Matthews'],
[],
[],
[],
[],
[],
[],
[],
[],
['Senate'],
['illness', 'mental illness', 'RT'],
[],
[],
[],
[],
[],
[],
['Healthcare bill'],
[],
[],
[],
['senate'],
[],
[],
['health insurance war'],
[],
[],
['GOP House'],
[],
['same drooling moron'],
[],
[],
[],
['GOP'],
['Congress vote', 'vote', 'Congress', 'House'],
[],
[],
['GOP'],
[],
[],
['Senate', 'WV'],
[],
[],
[],
['Senate'],
['United States', 'United States', 'United States', 'America', 'West America', 'West America', 'East America', 'East America', 'Flyover America'],
['Haiku'],
['Senate'],
[],
[],
['healthcare'],
[],
[],
['Michael Savage'],
[],
[],
[],
['Congress'],
[],
[],
[],
[],
[],
['US Senate'],
[],
['US'],
[],
[],
[],
['GOP'],
[],
[],
['health insurance'],
[],
['Republican party'],
[],
['GOP'],
['Mt. Everest'],
['GOP'],
[],
[],
[],
[],
['GOP'],
[],
[],
['Sims City'],
['universal healthcare'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['GOP'],
[],
[],
[],
[],
[],
[],
[],
['America'],
[],
[],
['food'],
[],
[],
[],
[],
[],
['chemotherapy', 'chemotherapy'],
[],
[],
['GOP'],
[],
[],
[],
[],
['GOP'],
['GOP'],
[],
[],
['NC'],
[],
[],
[],
[],
[],
['healthcare revisions'],
[],
[],
[],
[],
[],
[],
['Senate', 'USA'],
[],
['law condemning women'],
[],
['GOP'],
['healthcare vote', 'California'],
['Senate on Obamacare', 'House vote'],
[],
['President', 'a politician'],
[],
['erectile dysfunction'],
[],
['Congress'],
[],
['Pa.'],
[],
[],
[],
[],
[],
['Senate', 'House vote'],
[],
[],
['CNN', 'CNN'],
['Arizona'],
[],
[],
[],
[],
[],
[],
['America', "today's House vote"],
[],
['senate'],
[],
[],
[],
[],
[],
['GOP'],
[],
['President'],
[],
['cancer', 'cancer treatment'],
[],
['A Lonely Hunter'],
[],
[],
[],
[],
[],
[],
[],
['US'],
[],
['Issa', 'Cali'],
[],
['healthcare bill'],
['GOP'],
[],
[],
[],
['health services'],
['pass healthcare bill'],
[],
[],
[],
[],
[],
[],
[],
['Andy Biggs', 'Congressional  House'],
[],
['America', 'health insurance'],
[],
['PTSD'],
[],
[],
['Grand Ole Putin Party'],
[],
[],
[],
[],
['Congress'],
[],
['energy', 'GOP'],
[],
['Special ed services'],
['Jason Chaffetz', 'the House Oversight Chair'],
['The Mich Stepping Stones Daily'],
['Senate'],
['America'],
[],
['GOP'],
[],
[],
[],
[],
['GOP'],
[],
['whatever mental disorder'],
[],
[],
['GOP'],
[],
[],
[],
[],
[],
['Congress'],
[],
[],
[],
[],
[],
['healthcare', 'Americans w/ lung disease'],
[],
[],
['USA'],
[],
['GOP'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['w/o health insurance'],
['GOP'],
['America'],
[],
[],
['Ohio'],
[],
['US'],
[],
[],
[],
[],
['GOP'],
[],
[],
[],
[],
[],
[],
[],
['GOP'],
[],
['Senate', 'GOP'],
[],
['GOP'],
[],
[],
[],
[],
['Iran'],
[],
[],
[],
['GOP'],
[],
['own insurance plan'],
[],
[],
['New York Times', 'The New York Times'],
[],
[],
[],
[],
[],
['health insurance'],
[],
[],
[],
['BC'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['Senate'],
[],
[],
[],
[],
['kindly usher'],
['Maryland', 'representative'],
[],
[],
[],
[],
[],
[],
[],
['away healthcare'],
[],
[],
[],
[],
[],
[],
['Messenger'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['gov.'],
['Senate'],
['a retired special education teacher'],
[],
['single page fundraiser for Democrats'],
[],
[],
[],
['Bush'],
[],
['Darrell Issa', 'he'],
[],
['ovarian cancer', 'Testicular cancer'],
[],
[],
[],
[],
['The President and the Future Speaker'],
['GOP', 'Rep. Joe Kennedy'],
[],
['Arya Stark'],
[],
['GOP', 'CNN'],
['GOP'],
[],
['senate'],
[],
[],
[],
[],
['GOP', 'Senate'],
['GOP'],
['America'],
['White House', 'Bill Clinton', 'his'],
[],
['online dictionaries'],
['Mira Mira Mira'],
['NETFLIX', 'SJW', 'Bill Nye'],
[],
[],
[],
[],
[],
[],
[],
[],
['Senate'],
[],
[],
[],
['healthcare', 'GOP'],
[],
['healthcare plan'],
[],
[],
[],
[],
['healthcare'],
[],
['RT'],
[],
["It's Always Sunny In Philadelphia"],
['state of CA'],
['America'],
[],
[],
['VP @POTUS', '@VP'],
['GOP'],
['president', 'America'],
['steals insurance'],
[],
[],
[],
[],
['GOP'],
[],
['California', 'GOP'],
['GOP'],
[],
[],
[],
['EUROPE'],
['UK', 'EUROPE'],
[],
[],
['Blair', 'Europe', 'Hitler', 'Theresa May', 'Thatcher'],
['Russia'],
[],
[],
['WOW!'],
[],
['Netanyahu'],
['Ukraine'],
['Salvador Sobral', 'his', 'him'],
['Portugal'],
['Israel'],
['Bulgaria'],
[],
['THE BACKGROUND DANCER'],
['Sweden'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['Spain'],
[],
[],
['Germany'],
[],
[],
[],
[],
[],
[],
[],
[],
['Croatia'],
['USA'],
['Wee Bum'],
[],
[],
[],
[],
[],
['US'],
[],
[],
[],
['Moldova', 'Romania'],
[],
[],
[],
['Portugal', 'Russia', 'Ukraine', 'Bosnia'],
[],
[],
[],
['Romania'],
[],
['Tokio Hotel'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['Portugal', 'UN'],
[],
[],
[],
[],
[],
['Portugal', 'POrtUgAl', 'Salvador'],
[],
[],
[],
[],
[],
[],
['Europe'],
[],
[],
['The Netherlands', 'Disney'],
[],
['pls RT'],
['Salvador Sobral', 'Portugal'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['Cyprus'],
[],
['Salvador', 'his'],
['Middle East'],
[],
[],
[],
[],
[],
[],
[],
[],
['UK'],
[],
[],
[],
[],
[],
[],
['Portugal'],
[],
['Spain'],
['GIBRALTAR', 'SPAIN'],
['Spain'],
['Spain'],
['GIF'],
[],
[],
[],
[],
[],
[],
[],
['Luisa', 'Salvador'],
[],
['US'],
[],
[],
[],
[],
['Portugal', 'Salvador'],
['Salvador Sobral'],
['Salvador Sobral'],
['israel europe', 'israel'],
['RT'],
['Sweden', 'RT'],
['Portugal'],
['Portugal'],
['Romania'],
[],
['CNN'],
[],
['DreamWorks'],
['Europe'],
[],
[],
['AUSTRALIA', 'BRITS'],
[],
['Portugal'],
['Portugal'],
['Portugal'],
['Portugal'],
['Portugal', 'Portugal', 'Portugal'],
[],
[],
[],
[],
[],
['US'],
[],
['Our Ukraine'],
[],
[],
[],
[],
['OH'],
[],
[],
[],
[],
[],
[],
[],
['Gay Lover'],
[],
[],
[],
['Wales', 'UK'],
[],
[],
[],
[],
['Ireland', 'UK'],
['U.K', 'Ireland'],
[],
[],
['singer'],
[],
[],
['Justin Timberlake', 'Nathan Trent'],
[],
[],
[],
['Dad'],
['Hotel JuST WASSSSSSSSS'],
[],
['Portugal'],
[],
[],
[],
['Moldova'],
['Malta'],
[],
[],
[],
[],
[],
[],
['Ruslana'],
['Lucie Jones'],
[],
[],
['Australia'],
['prince', 'Azerbaijan'],
['RT'],
[],
['queen', 'Lee Lin', 'She', 'She'],
[],
[],
[],
[],
[],
[],
['Europe', 'Italy'],
['Portugal'],
['Britain'],
[],
[],
['Portugal'],
[],
['Israel', 'Israel'],
['Israel', 'Song Contest'],
['Israel', 'gif'],
['Poland'],
[],
['Ireland'],
['food'],
[],
['your commentator', 'graham norton'],
[],
[],
['Moldova'],
[],
['Portugal', 'Sweden'],
['UK'],
['UK', 'Europe'],
[],
[],
[],
['Diane Abbott'],
[],
[],
[],
[],
['Australia'],
[],
['Greece'],
[],
[],
[],
['Salvador'],
[],
[],
['USA'],
[],
[],
[],
[],
[],
[],
[],
['Hillary Clinton'],
['Hillary Clinton'],
['Europe'],
['Antarctica', 'South America', 'Australia', 'North America', 'Africa', 'Europe'],
[],
[],
[],
[],
['Anna Wintour', 'Gigi Hadid', 'Brad Pitt'],
[],
[],
[],
[],
['heart transplant'],
[],
['Florida'],
[],
[],
['Greece', 'Greece', 'Portugal', 'Portugal'],
[],
[],
[],
[],
[],
['Germany'],
['George Soros'],
['George Soros', 'Europe'],
['George Soros', 'he'],
[],
[],
[],
[],
[],
[],
['France'],
[],
[],
[],
[],
['Www', 'Www.Whyislam.p'],
[],
[],
['Europe', 'Portugal'],
[],
[],
['Germany', 'David Guetta', 'DavID gUeTta'],
[],
[],
['Europe', 'Europe', 'Australia'],
['Europe'],
[],
['Croatia'],
['Ryan Gosling'],
[],
[],
[],
[],
[],
[],
[],
[],
[],
['Australia'],
[],
[],
['Sweden', 'Romania', 'CROATIA'],
[],
['Ukraine'],
['Lisbon', 'Portugal'],
['Moldova'],
[],
[],
[],
[],
[],
[],
['Buzzfeed'],
['Britain', 'Lucie Jones', 'her'],
['Britain'],
[],
[],
[],
[],
[],
[],
['Bill'],
[],
[],
[],
[],
[],
[],
['BBC'],
['BBC'],
['Gay Lover', 'Barack Obama'],
['Azerbaijan'],
['AUSTRALIA'],
['Australia'],
['Europe', 'Australia'],
[],
[],
[],
['Ukraine'],
['Australia', 'the commonwealth games'],
[],
[],
[],
[],
['Salvador Sobral', 'Portugal'],
[],
['Twitter'],
[],
['Amar Pelos Dois', 'his', 'Luisa', 'Salvador'],
['Alexander Rybak'],
[],
[],
['UK'],
['worker', 'Western Cape\nGeneral Office'],
['ADMINISTRATOR', 'NELSPRUIT'],
['Natal'],
['Bath', 'Gauteng\nSuperior Spa'],
[],
['Switzerland', 'Céline Dion', 'Australia'],
['UK'],
[],
['Australia', 'Europe'],
[],
['Ireland'],
['UK'],
['Portugal'],
['UK'],
['Slovenia'],
[],
['Portugal'],
[],
[],
[],
['Champions League', 'World Cup'],
[],
[],
[],
[],
[],
[],
['Chester'],
[],
['Australia'],
[],
['Portugal'],
[],
[]]

my_list=my_list+my_list2
print(len(my_list))
print(tweets.tail(2))
# tweets=tweets[:1499:]
# print(tweets[-1::])
# tweets=tweets[:-1:]

print(len(tweets))

tweets['calai_cnd']=my_list

tweets.to_csv("all_of.csv", sep=',', encoding='utf-8')

# print(tweets.tail(5))
# print(topic_merged_1_23.tail())
# print("BITERRRRRRRRRRRRRRRRRRRRRRRRR")
# topic_merged_1_24=topic_merged_1_2[200000:300000]
# print(topic_merged_1_24.head())
# print(len(topic_merged_1_24))
# print(topic2.tail())
# topic_merged_1_2.to_csv("merged_1mil_second_set.csv", sep=',', encoding='utf-8')
# topic2=pd.read_csv("merged_1mil_second_set.csv",sep =',')
# print(len(topic2))
# print(topic2.tail())


# # annotated=[ "NO" for i in range(len(topic_merged_1_2))]

# # topic_merged_1_2['annotated']=annotated
# print(topic_merged_1_2.tail())
# print(len(topic_merged_1_2))

# topic_merged_1_2.to_csv("merged_1mil_second_set.csv", sep=',', encoding='utf-8')
